### ISSUE TITLE
Build failure, Ubuntu 12.04

### ISSUE THREAD

**Issue by benjschiller** [daler/pybedtools#85]
Update: I was able to compile with C=gcc-4.6 CXX=g++-4.6 ../bin/python setup.py build. Maybe this is an upstream issue with gcc 4.4?

I can't figure out why pybedtools isn't compiling. I installed bedtools with no problems on the system, and I think that all the required packages are installed. I even tried installing pybedtools in a virtualenv to make absolutely sure there were no conflicting packages.

Here's the output:

... (copying a bunch of files)
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pybedtools
creating build/temp.linux-x86_64-2.7/src
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc/ -I/usr/include/python2.7 -c pybedtools/cbedtools.cpp -o build/temp.linux-x86_64-2.7/pybedtools/cbedtools.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
In file included from /usr/include/c++/4.4/vector:61,
                 from pybedtools/cbedtools.cpp:314:
/usr/include/c++/4.4/bits/stl_algobase.h:73: error: expected ‘{’ before ‘_GLIBCXX_VISIBILITY’
/usr/include/c++/4.4/bits/stl_algobase.h:73: error: expected constructor, destructor, or type conversion before ‘(’ token
In file included from /usr/include/c++/4.4/new:40,
                 from /usr/include/c++/4.4/ext/new_allocator.h:33,
                 from /usr/include/c++/4.4/bits/c++allocator.h:34,
                 from /usr/include/c++/4.4/bits/allocator.h:48,
                 from /usr/include/c++/4.4/vector:62,
                 from pybedtools/cbedtools.cpp:314:
/usr/include/c++/4.4/exception:35: error: expected ‘}’ before end of line
/usr/include/c++/4.4/exception:35: error: expected declaration before end of line
error: command 'gcc' failed with exit status 1
